// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:55c82dc7-817a-47f9-b4a1-0e5a8677295a",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_akqDiMTmR",
    "aws_user_pools_web_client_id": "414s3uh3p2c9rvpmfdhqb25dhn",
    "aws_mobile_analytics_app_id": "c57f001bf2694ecf8e9065950a128b18",
    "aws_mobile_analytics_app_region": "eu-west-1",
    "aws_content_delivery_bucket": "doorlarm-20190207135300-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://doorlarm-20190207135300-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
